<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>po</string>
		<string>pot</string>
		<string>potx</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>gettext Portable Object (PO)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?=#[:,|~=.]|msg(?:id|str)(?!\s+""))</string>
			<key>comment</key>
			<string>Start of body of document, after header</string>
			<key>end</key>
			<string>\b\B</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#header</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\S)</string>
					<key>contentName</key>
					<string>meta.block.po</string>
					<key>end</key>
					<string>^\s*$\n?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.fold.end.po</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#line-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blocks</string>
				</dict>
			</array>
		</dict>
		<key>comma-separators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.po</string>
				</dict>
			</array>
		</dict>
		<key>doc-block-kvp-generic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G([\w-]+)((:)\s*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.mapping.key.po variable.language.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.mapping.po</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.po</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.mapping.value.po</string>
					<key>end</key>
					<string>(?=\\n?")</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escapes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#semicolon-separators</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=</string>
							<key>name</key>
							<string>punctuation.separator.key-value.po</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>doc-block-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"$\n</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.po</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string.po string.quoted.double.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc-block-kvp-generic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>doc-block-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=")</string>
					<key>end</key>
					<string>\s*$\n?</string>
					<key>name</key>
					<string>comment.block.documentation.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc-block-string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>flags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bfuzzy\b</string>
					<key>name</key>
					<string>storage.modifier.po</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:no-)?(?:[a-z]+|object-pascal|c\+\+|modula2)(?:-brace|-internal|-plural|-printf)?-format</string>
					<key>name</key>
					<string>variable.annotation.po</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bno-wrap\b</string>
					<key>name</key>
					<string>variable.annotation.po</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(range)\b(:?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.annotation.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?![\s\d.])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#integers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma-separators</string>
				</dict>
			</array>
		</dict>
		<key>header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-comments-translator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc-block-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>integers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>meta.number.integer.decimal.po constant.numeric.value.po</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bmsgid(?:_plural)?\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgid.po</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.label.po</string>
					<key>end</key>
					<string>(?![\s"])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brackets.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.begin.po</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.decimal.po constant.numeric.value.po</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.end.po</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\bmsgstr\b((\[)(\d*)(\]))?</string>
					<key>name</key>
					<string>keyword.control.msgstr.po</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brackets.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.begin.po</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.decimal.po constant.numeric.value.po</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.end.po</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\bmsgctxt\b((\[)(\d*)(\]))?</string>
					<key>name</key>
					<string>keyword.control.msgctxt.po</string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-comments-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comments-sourceref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comments-flag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comments-extracted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comments-translator</string>
				</dict>
			</array>
		</dict>
		<key>line-comments-extracted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#\.</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.extracted.po</string>
				</dict>
			</array>
		</dict>
		<key>line-comments-flag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#[,=]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.flag.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#flags</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comma-separators</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>line-comments-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#[|~]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.previous.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>line-comments-sourceref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.reference.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.sequence.po</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>meta.number.integer.decimal.po constant.numeric.value.po</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(:)(\d+)(?=\s)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#semicolon-separators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#paths</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>line-comments-translator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.translator.po</string>
				</dict>
			</array>
		</dict>
		<key>paths</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\S)</string>
					<key>end</key>
					<string>(?=[:\s])</string>
					<key>name</key>
					<string>entity.name.path.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>/</string>
							<key>name</key>
							<string>punctuation.separator.sequence.po</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>semicolon-separators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.separator.po</string>
				</dict>
			</array>
		</dict>
		<key>string-escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.po</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.po</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string.po string.quoted.double.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string-escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.po</string>
	<key>uuid</key>
	<string>F07730BD-59BC-41D0-AC3F-4AB2DCB6C54A</string>
</dict>
</plist>
